# -*- coding: utf-8 -*-
"""
配置模块
将所有配置信息分模块管理，提供统一的配置接口
"""

from .basic_config import *
from .psychological_config import *
from .questionnaire_config import *
from .prompt_config import *
from .generation_config import *

# 向后兼容：提供原始的导入方式
__all__ = [
    # 基本配置
    'MIN_AGE', 'MAX_AGE', 'GENDERS', 'EDUCATION_LEVELS', 'OCCUPATION_STATUS',
    'MARITAL_STATUS', 'DEPRESSION_TAGS', 'NON_DEPRESSED_LEVELS', 'DEPRESSED_LEVELS',
    
    # 心理配置  
    'PERSONALITY_TRAITS', 'LANGUAGE_STYLES', 'EXPRESSION_TONES', 'HIDING_TENDENCIES',
    'CORE_BELIEFS', 'INTERMEDIATE_BELIEFS', 'DEPRESSED_BELIEFS', 'COPING_STRATEGIES',
    'MAIN_EMOTIONS', 'AUTOMATIC_THOUGHTS', 'TYPICAL_BEHAVIORS',
    'DEPRESSION_LEVEL_EMOTIONS', 'DEPRESSION_LEVEL_THOUGHTS', 'DEPRESSION_LEVEL_BEHAVIORS',
    'DEPRESSION_PERSONALITY_TENDENCIES', 'PHQ9_SCORE_RANGES', 'SDS_SCORE_RANGES',
    'PATIENT_HISTORY_TEMPLATES', 'DEPRESSION_LEVEL_HISTORIES',
    'HEALTHY_CORE_BELIEFS', 'HEALTHY_INTERMEDIATE_BELIEFS', 'HEALTHY_COPING_STRATEGIES',
    'HEALTHY_MAIN_EMOTIONS', 'HEALTHY_AUTOMATIC_THOUGHTS', 'HEALTHY_TYPICAL_BEHAVIORS',
    'HEALTHY_HISTORY_TEMPLATES',
    
    # 量表配置
    'PHQ9_QUESTIONNAIRE', 'SDS_QUESTIONNAIRE',
    
    # 提示词配置
    'PROMPT_SCENARIOS', 'EXPRESSION_STYLES', 'TIME_PERSPECTIVES',
    'SITUATIONAL_TRIGGERS', 'SOCIAL_MEDIA_CONTEXTS',
    
    # 生成配置
    'DATA_GENERATION_CONSTRAINTS', 'LANGUAGE_STYLE_MAPPING'
]
